version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      parsers:
        patterns:
          - "@babel/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "espree"
          - "typescript"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
