// Alternatives for each client finding. A variant is shown when its checks occur; several variants may match one check.
// The wording is conditional where reachability or attacker control has not been established by the scan.
// [label, check ID pattern, description, implication, how to distinguish this case, recommendation]
export const VARIATIONS = {
  'Renderer Isolation Weakened': [
    ['Node access in a renderer', /^(NODE_INTEGRATION|HTTP_RESOURCES_WITH_NODE_INTEGRATION|RUNTIME_NODE_INTEGRATION)/,
      'A renderer may have direct Node.js capability.', 'If untrusted content runs script in that renderer, it may access Node APIs and the local system.',
      'Identify the affected window and confirm whether untrusted pages, documents or messages can execute script there.', 'Disable nodeIntegration and expose only narrow main-process operations through a preload.'],
    ['Isolation or sandbox disabled', /^(CONTEXT_ISOLATION|SANDBOX|RUNTIME_CONTEXT_ISOLATION|RUNTIME_SANDBOX)/,
      'The renderer may share a JavaScript world with its preload or lack a process sandbox.', 'If script injection occurs, weaker isolation may expose preload data or increase the impact of a renderer compromise.',
      'Compare the packaged webPreferences with runtime window settings and the origin loaded in each window.', 'Enable contextIsolation and sandbox, then test the preload bridge.'],
    ['Additional privilege sharing', /^(REMOTE_MODULE|AFFINITY)/,
      'Legacy remote access or process affinity can combine different trust levels.', 'If a lower-trust page shares these capabilities, it may gain access to privileged state.',
      'Trace remote imports or affinity values to the windows that consume them.', 'Remove remote and avoid sharing a renderer process between different trust levels.'],
  ],
  'Chromium Security Features Disabled': [
    ['Origin or transport protections', /^(WEB_SECURITY|INSECURE_CONTENT|RUNTIME_WEB_SECURITY|CUSTOM_ARGUMENTS)/,
      'Browser origin, certificate or mixed-content protections may be weakened.', 'If attacker-controlled content loads, it may cross origins or accept resources the browser would normally reject.',
      'Inspect the command-line switches and effective window settings; confirm the affected origin and resource.', 'Remove security-disabling switches and settings; solve cross-origin needs with scoped server policy.'],
    ['Experimental or legacy capability', /^(EXPERIMENTAL_FEATURES|BLINK_FEATURES|WEBGL|WEBSQL|PLUGINS|NAVIGATE_ON_DRAG_DROP)/,
      'An optional browser capability is enabled or left available.', 'The impact depends on whether the affected page uses that capability and what content it loads.',
      'Check the runtime setting and determine whether the feature is needed by a production workflow.', 'Disable unused capabilities and keep required ones restricted to trusted windows.'],
    ['Warning or keyboard safeguard', /^(SECURITY_WARNINGS_DISABLED|SECUREKEYBOARDENTRY)/,
      'A development warning or sensitive-input safeguard may be missing.', 'The result may reduce visibility into insecure configuration or expose typed secrets in a local threat scenario.',
      'Inspect the packaged setting on the relevant operating system and reproduce the sensitive-input flow.', 'Restore security warnings and enable secure keyboard entry where the platform and workflow require it.'],
  ],
  'Privileged APIs Exposed to Untrusted Content': [
    ['Broad preload bridge', /^(CONTEXT_BRIDGE_EXPOSURE|RUNTIME_PRELOAD_FOREIGN_ORIGIN)/,
      'A page may see a broad preload API or a preload on an unexpected origin.', 'If lower-trust content reaches the window, it may invoke operations that were intended only for trusted pages.',
      'List exposed methods, origins and their main-process handlers; verify the origin of a live caller.', 'Expose a minimal typed API and validate origin and arguments again in the main process.'],
    ['Shared session between trust levels', /^(WINDOW_SESSION|RUNTIME_WINDOW_SESSION)/,
      'Windows of differing trust may share cookies, storage or permission grants.', 'A lower-trust page could inherit session state if the same partition is reused.',
      'Compare partition identifiers and live origins for the affected windows.', 'Use separate sessions and permission policies for different trust levels.'],
  ],
  'IPC Handlers Trust Renderer Input': [
    ['Sender not restricted', /^(IPC_SENDER_VALIDATION|RUNTIME_MARKER_IPC)/,
      'An IPC handler may accept calls from a renderer or frame outside the intended origin.', 'If an untrusted page can send on the channel, it may request a privileged operation.',
      'Trace the channel to its handler and check event.senderFrame.url against a live sender.', 'Validate the sender frame before processing any argument.'],
    ['Arguments or file paths trusted', /^(IPC_HANDLER|IPC_FILE_ACCESS)/,
      'The handler may use renderer-controlled arguments in a sensitive operation.', 'If a caller controls a path or command argument, it may affect files or operating-system actions beyond its role.',
      'Inspect the handler body and exercise a benign out-of-scope argument in an authorised test.', 'Validate types and constrain paths and operations in the main process.'],
    ['Unused or unexpected channel', /^IPC_CHANNEL_MAP/,
      'An exposed channel may not appear in the observed renderer traffic.', 'The risk depends on whether served code or another renderer can actually call it.',
      'Compare registered channels with the shipped renderer and a representative watch session.', 'Remove unused handlers or document and enforce the intended callers.'],
  ],
  'Unsafe Hand-off of URLs and Files to the Operating System': [
    ['External URL or protocol', /^(OPEN_EXTERNAL|RUNTIME_OPEN_EXTERNAL|RUNTIME_MARKER_OPEN_EXTERNAL)/,
      'A URL reaches the operating-system protocol handler.', 'If a user clicks a crafted link, a non-web scheme or network share may launch another handler or expose credentials.',
      'Check which schemes and hosts reach openExternal; distinguish a recorded hand-off from attacker control.', 'Allowlist schemes and destinations before calling openExternal.'],
    ['Non-web protocol launch', /^(OPEN_EXTERNAL|RUNTIME_OPEN_EXTERNAL|RUNTIME_MARKER_OPEN_EXTERNAL)/,
      'A file, custom or application protocol may be accepted by the hand-off.', 'If a crafted link can select an unsafe scheme, the host may launch a local application or file handler.',
      'Test a benign custom-protocol or file URL and record whether the app blocks it before the OS hand-off.', 'Reject non-web schemes unless a specific handler and destination are required.'],
    ['Network-share credential exposure', /^(OPEN_EXTERNAL|RUNTIME_OPEN_EXTERNAL|RUNTIME_MARKER_OPEN_EXTERNAL)/,
      'A UNC or network-share target may be passed to the host.', 'On systems that authenticate to a remote share, a user click could disclose authentication material to that share.',
      'Check whether an untrusted link can pass a network-share target; do not collect real credentials during validation.', 'Reject UNC, SMB and equivalent network-share destinations from untrusted content.'],
    ['File path handed to the host', /^(OPEN_PATH|SHOWITEMINFOLDER|RUNTIME_OPEN_PATH|RUNTIME_MARKER_OPEN_PATH)/,
      'A path reaches an API that opens or reveals a local file.', 'If untrusted content controls the path, an executable or unintended document may be opened.',
      'Trace path construction, base-directory containment and the final extension in a benign test.', 'Resolve paths under an allowed directory and reject executable extensions and traversal.'],
    ['Executable file path', /^(OPEN_PATH|RUNTIME_OPEN_PATH|RUNTIME_MARKER_OPEN_PATH)/,
      'The opened path may resolve to a script, shortcut or executable.', 'If the renderer can select that path, the operating system may execute it under the user’s account.',
      'Use a harmless test file to verify the path and extension policy without running an untrusted executable.', 'Block executable extensions and require explicit user choice for any program launch.'],
    ['Download or shortcut destination', /^(DOWNLOAD|WRITE_SHORTCUT)/,
      'A download or shortcut may be written to an unsafe location or target.', 'If content controls the destination, the app may place an unexpected file or launcher on disk.',
      'Inspect the final target path and whether the input originates from a page or fixed app configuration.', 'Restrict output folders and targets, and require explicit user intent where appropriate.'],
  ],
  'Code or Command Execution from Untrusted Data': [
    ['Shell command construction', /^(COMMAND_INJECTION|RUNTIME_MARKER_COMMAND)/,
      'A value may enter a command line or process invocation.', 'If an untrusted sender controls shell metacharacters or arguments, code may run with application privileges.',
      'Trace the value to the process API; use a harmless marker to separate data flow from actual command execution.', 'Avoid a shell, use execFile or spawn with a fixed program and validated argument array.'],
    ['Dynamic code evaluation', /^DANGEROUS_FUNCTIONS/,
      'A string may be evaluated as JavaScript or another executable language.', 'If lower-trust input reaches the evaluator, the renderer may run attacker-supplied code.',
      'Identify the evaluated value and its source; test with a benign marker in an isolated environment.', 'Replace evaluation with data parsing or a fixed dispatch table.'],
  ],
  'Microsoft Word Integration': [
    ['Word launch command', /^WORD_LAUNCH/,
      'The Word launch path may construct a command or accept a document name from outside the app.', 'If a path is not validated, the app may open an unintended document or mis-handle launch arguments.',
      'Inspect the Word invocation and confirm the final argument array and document location.', 'Use a fixed executable with an argument array and constrain the document path.'],
    ['Document provenance and Protected View', /^(WORD_LAUNCH|RUNTIME_OPEN_PATH|RUNTIME_MARKER_OPEN_PATH)/,
      'A document may be opened after losing its Mark-of-the-Web provenance.', 'If a downloaded document lacks Zone.Identifier when Word opens it, Protected View may not apply as expected.',
      'On Windows, inspect the actual opened file with Get-Item <doc> -Stream Zone.Identifier.', 'Preserve the provenance stream and avoid copying untrusted documents into a trusted location before opening.'],
  ],
  'Deep Link, Protocol and File Association Handling': [
    ['External handler input', /^(FILE_HANDLER|PROTOCOL_HANDLER|INSTALLER_FILE_HANDLER)/,
      'A registered link or file association supplies data to the app.', 'If an external sender controls parameters, an unsafe action or path may be selected.',
      'Inspect the registered command and follow a benign crafted link or file through the parser.', 'Parse input with a fixed schema, allowlist actions and reject paths outside the intended scope.'],
    ['Privileged custom scheme or file URL', /^(PROTOCOL_PRIVILEGES|FILE_PROTOCOL|UNTRUSTED_LOAD_URL)/,
      'A custom scheme or file URL may receive more privileges than needed.', 'If untrusted input selects the resource, it may reach local files or a privileged renderer.',
      'Check scheme privileges, resource resolution and the final URL loaded by each window.', 'Grant only necessary scheme privileges and serve resources from an explicit allowlist.'],
  ],
  'Insufficient Navigation and Window Controls': [
    ['Top-level navigation or redirect', /^(LIMIT_NAVIGATION|NAVIGATION_REDIRECT|RUNTIME_NAVIGATION|RUNTIME_REDIRECT|RUNTIME_MARKER_NAVIGATION)/,
      'A window may navigate away from the intended origin, including after a redirect.', 'If it retains preload or session access, an external page may inherit more capability than intended.',
      'Exercise a benign external link and redirect while recording the final URL and window settings.', 'Block unapproved destinations in will-navigate and will-redirect.'],
    ['Popup or middle-click', /^(WINDOW_OPEN_HANDLER|AUXCLICK|ALLOWPOPUPS|RUNTIME_NEW_WINDOW|RUNTIME_MARKER_NEW_WINDOW)/,
      'A new window may be created from page content without a restrictive policy.', 'A crafted link may open a privileged child window or hand an unsafe URL to the host.',
      'Test a benign popup and middle-click in the affected renderer and inspect its options.', 'Deny new windows by default and handle approved web links through a URL allowlist.'],
    ['Embedded content', /^(WEBVIEW|IFRAME_SANDBOX|RUNTIME_WEBVIEW)/,
      'An embedded view or frame may load content with weak sandboxing.', 'If the child loads lower-trust content, its privileges or navigation policy may increase its reach.',
      'Inspect webview attachment and iframe sandbox attributes for the actual loaded source.', 'Avoid webview where possible; otherwise validate src and force restrictive preferences.'],
  ],
  'Missing Permission Handlers': [
    ['Permission request callback', /^(PERMISSION_REQUEST_HANDLER|RUNTIME_PERMISSION$)/,
      'The session may grant a requested browser capability without an application policy.', 'A page could receive camera, geolocation or notification access if the request is not checked.',
      'Request a benign permission from the affected origin and record the handler and decision.', 'Set a request handler that checks origin and permission and denies everything else.'],
    ['Synchronous permission check', /^RUNTIME_PERMISSION_CHECK/,
      'A permission check may be allowed without a matching check handler.', 'An API that uses synchronous permission checks could proceed even where request handling is restricted.',
      'Inspect setPermissionCheckHandler and observe the origin and permission in a watch session.', 'Add a check handler using the same explicit origin and capability policy.'],
  ],
  'Cross-Site Scripting Exposure in Content Rendering': [
    ['HTML sink or editor', /^(XSS_SINK|RICH_TEXT_EDITOR|RUNTIME_DOM_INJECTION|RUNTIME_HTML_ENDPOINT)/,
      'A sink or editor may place externally supplied markup into the page.', 'If another user controls that value, script-bearing markup may execute in the viewer’s renderer.',
      'Follow a harmless unique marker from its input to the rendered sink; distinguish text from live HTML and script execution.', 'Use textContent for text and sanitise the limited HTML that must remain.'],
    ['Sanitiser or framework bypass', /^(SANITIZER_CONFIG|ANGULAR)/,
      'A sanitiser setting or framework trust API may permit active markup.', 'If untrusted data enters that path, event handlers or URLs may bypass the expected encoding boundary.',
      'Inspect the configured allowlist and the exact binding that consumes the value.', 'Restore safe defaults and avoid trust-bypass APIs for user content.'],
    ['Runtime reflection or message', /^(RUNTIME_MARKER|RUNTIME_ACTIVE_SCRIPT|RUNTIME_CAMPAIGN_SCRIPT|TRAFFIC_WS_HTML_MESSAGE|TRAFFIC_REFLECTED_INPUT)/,
      'A marker, WebSocket message or reflected value appeared in a rendering path.', 'A live HTML observation is not proof of cross-account execution; a confirmed script probe supports a stronger conclusion.',
      'Compare the source user, destination view, DOM interpretation and execution signal from the same session.', 'Encode or sanitise at the output boundary and limit the renderer with CSP.'],
    ['Markup without proven execution', /^(RUNTIME_MARKER|RUNTIME_MARKER_SINK)/,
      'A marker was rendered as live markup or reached an HTML sink.', 'This supports a rendering problem but does not alone prove script execution or a cross-account path.',
      'Check the same marker in the destination DOM and record whether a harmless script can run.', 'Remove the unsafe sink or sanitise the value before rendering.'],
    ['Script execution observed', /^(RUNTIME_ACTIVE_SCRIPT|RUNTIME_CAMPAIGN_SCRIPT)/,
      'A benign script probe executed during a configured workflow.', 'The confirmed execution has higher impact; the account boundary and renderer privileges still determine its reach.',
      'Match the execution event to the saved input, destination user and renderer settings in the same session.', 'Fix the source-to-sink path and test the change using the same benign probe.'],
  ],
  'Missing or Weak Content Security Policy': [
    ['No effective policy', /^(CSP$|CSP_DIRECTIVES)/,
      'A page may have no enforceable Content Security Policy.', 'If markup injection occurs, the browser has no policy boundary to limit script execution.',
      'Check the live response headers and meta elements for an enforceable policy, including redirects and frames.', 'Ship a restrictive policy in headers or a suitable meta element for every relevant page.'],
    ['Unsafe script directives', /^(CSP$|CSP_DIRECTIVES)/,
      'A present policy may still permit inline code, evaluation or broad script sources.', 'If untrusted markup reaches the page, permissive script directives may allow it to execute.',
      'Inspect the effective script-src directive, nonces, hashes and report-only status in the affected window.', 'Remove unsafe-inline and unsafe-eval where feasible and allowlist only necessary script sources.'],
    ['Runtime violation or mismatch', /^RUNTIME_CSP/,
      'The runtime policy or a CSP violation differs from the expected configuration.', 'A violation may reveal blocked content or a legitimate flow that still depends on unsafe policy.',
      'Record the effective runtime policy and violation details before changing it.', 'Fix the underlying script or resource loading and keep the policy restrictive.'],
  ],
  'Document Parsing Risks': [
    ['Untrusted document intake', /^DOCUMENT_PIPELINE/,
      'An imported document reaches a parser or conversion pipeline.', 'A malformed file may exercise vulnerable parser code if the app accepts that format.',
      'Identify the accepted formats, parser and isolation boundary; use a benign malformed fixture where authorised.', 'Validate type and size, keep parsers current and isolate conversion.'],
    ['Rendered conversion output', /^DOCUMENT_PIPELINE/,
      'Document conversion may produce HTML or linked resources for a renderer.', 'If active markup or external relationships survive conversion, a viewer may encounter content it did not authorise.',
      'Compare a harmless document’s converted output with the renderer’s HTML and resource requests.', 'Sanitise generated HTML and block unexpected external resources before rendering.'],
  ],
  'Insecure Electron Fuse Configuration': [
    ['Local Node entry points', /^(FUSES|PACKAGED_FUSES)/,
      'RunAsNode or Node option fuses may leave local execution entry points available.', 'A person who can launch or alter the app locally may use those capabilities under the app identity.',
      'Read the packaged fuse values and compare them with the build configuration.', 'Disable RunAsNode, NODE_OPTIONS and inspector argument fuses when not required.'],
    ['Asar integrity and loading', /^(FUSES|PACKAGED_FUSES)/,
      'The asar integrity or OnlyLoadAppFromAsar fuse may be off.', 'If a local actor can change packaged code, the app may load a modified archive.',
      'Check both fuse values and the executable’s embedded integrity digest.', 'Enable both fuses and embed and verify the archive integrity digest.'],
    ['Cookie or file-protocol privileges', /^(FUSES|PACKAGED_FUSES)/,
      'CookieEncryption or file-protocol privileges may differ from the intended release profile.', 'The impact depends on local profile access and whether a renderer uses privileged file URLs.',
      'Inspect the relevant fuse and confirm actual cookie storage and file URL use.', 'Enable cookie encryption and grant file-protocol privileges only when justified.'],
  ],
  'Application Code Not Protected Against Inspection or Tampering': [
    ['Source map exposure', /^SOURCE_MAP_SHIPPED/,
      'Source maps may reveal original application code in the distributed package.', 'Anyone with the package may learn implementation details and internal paths; this alone does not prove a vulnerability.',
      'Locate shipped .map files and check whether they include sourcesContent.', 'Exclude production maps or keep them on a private error-reporting service.'],
    ['Asar integrity', /^ASAR_INTEGRITY/,
      'The packaged asar may not be validated against a trusted digest.', 'A local actor who can change the installation could substitute application code if integrity is not enforced.',
      'Compare the packaged archive, embedded digest and integrity-related fuses.', 'Enable embedded asar integrity validation and load only from the asar.'],
  ],
  'Executable Signing and Exploit Mitigations (hardening)': [
    ['Publisher signature', /^CODE_SIGNING/,
      'The release executable or installer may be unsigned or its signature unverified.', 'A user may have less assurance about the publisher and integrity of a distributed update.',
      'Verify the signature with the operating system and record the signer and timestamp.', 'Sign and timestamp release binaries and installers with a trusted publisher identity.'],
    ['Platform exploit mitigations', /^BINARY_HARDENING/,
      'A binary may lack one or more platform memory-safety mitigations.', 'If a separate memory-corruption flaw exists, missing mitigations may make exploitation easier.',
      'Inspect mitigation flags in the exact shipped binary and any native modules.', 'Build native modules with supported hardening flags and ship current Electron binaries.'],
  ],
  'Insecure Update Mechanism': [
    ['Update feed transport', /^UPDATE_SECURITY/,
      'The update feed may be fetched without authenticated transport.', 'An on-path actor could influence metadata or release selection if no independent verification applies.',
      'Inspect the packaged feed URL and observe a benign update check.', 'Serve metadata and packages over HTTPS with certificate validation.'],
    ['Update signature or publisher', /^UPDATE_SECURITY/,
      'An update package may lack an enforced publisher or signature check.', 'If an attacker can replace a package, the client may install untrusted code.',
      'Check the updater implementation and a deliberately invalid test signature in an isolated environment.', 'Verify package signatures or publisher identity before installation.'],
  ],
  'Development and Debugging Features in Production': [
    ['Developer tooling or test hooks', /^(DEVTOOLS|DEVELOPMENT_CODE)/,
      'Developer tools or test-only features may be reachable in the release build.', 'A local user or injected content may gain additional introspection or actions through those features.',
      'Inspect the packaged build and exercise only the documented development entry point.', 'Remove test hooks and disable developer tools in production unless explicitly required.'],
    ['Logs, console secrets or exceptions', /^(DEBUG_LOGGING|RUNTIME_SECRET_IN_CONSOLE|RUNTIME_UNCAUGHT_EXCEPTION)/,
      'Logs or runtime errors may contain sensitive values or internal details.', 'Someone who can read logs or the console may obtain data beyond their role.',
      'Check the recorded line or watch event and its actual value and retention path.', 'Remove secrets from logs, restrict log access and handle errors without exposing data.'],
  ],
  'Hard-coded Secrets in the Application Package': [
    ['Credential or token in code', /^HARDCODED_SECRET/,
      'A token or credential-like value appears in distributed code or configuration.', 'If it is a live shared secret, anyone with the package may use it until it is revoked.',
      'Identify the provider, scope, validity and whether the value is a secret rather than a public identifier.', 'Rotate confirmed secrets and move privileged credentials to a server or OS-backed store.'],
    ['Public key or false positive', /^HARDCODED_SECRET/,
      'A detected high-entropy value may instead be a public client identifier or a test value.', 'No credential compromise follows if the value has no secret privileges.',
      'Verify the provider’s classification and effective permissions before raising the final impact.', 'Keep public identifiers narrowly scoped and remove test values from release builds.'],
  ],
  'Sensitive Data Stored Insecurely': [
    ['Plaintext credential or file', /^(STORAGE_(CREDENTIAL|SECRET)|SECRET_FILE_WRITE|PLAINTEXT_SECRETS)/,
      'A password, token or other secret may be stored without OS-backed protection.', 'Someone with access to the user profile or backup may recover the value.',
      'Identify the exact store and compare a benign canary before and after the save operation.', 'Use safeStorage or the operating-system credential store and clear obsolete plaintext copies.'],
    ['Application settings or cached responses', /^(ELECTRON_STORE_ENCRYPTION|STORAGE_CACHED_RESPONSES|STORAGE_COOKIE_AT_REST)/,
      'Settings, cookies or cached responses may persist sensitive data.', 'The impact depends on the data, encryption fuse and profile access.',
      'Inspect the exact stored value and protection without copying real user secrets into the report.', 'Keep credentials out of general settings, enable cookie encryption and prevent caching of sensitive responses.'],
  ],
  'Insecure Transport and Certificate Validation': [
    ['Cleartext HTTP or WebSocket', /^(HTTP_RESOURCES|RUNTIME_INSECURE_LOAD|TRAFFIC_CLEARTEXT_HTTP|TRAFFIC_WS_CLEARTEXT)/,
      'A request or loaded resource may use an unencrypted transport.', 'An on-path actor may read or alter that traffic, with greater impact for executable page resources or credentials.',
      'Confirm the final scheme and host in a capture or live load.', 'Use HTTPS and WSS for all relevant resources and endpoints.'],
    ['Certificate validation bypass', /^(CERTIFICATE|NODE_TLS_REJECT_UNAUTHORIZED|RUNTIME_CERTIFICATE_ERROR)/,
      'TLS certificate validation may be disabled or overridden.', 'An on-path actor could impersonate a server if the affected request accepts an invalid certificate.',
      'Identify the exact session, host and callback result; distinguish a rejected error from an accepted one.', 'Remove bypasses and trust only the intended CA and server identity.'],
    ['Credential transport or cookie flags', /^(TRAFFIC_BASIC_AUTH|TRAFFIC_INSECURE_COOKIE|COOKIE_FLAGS)/,
      'Authentication may use Basic credentials or a cookie without expected flags.', 'A credential may be exposed in transit or to script depending on the scheme and missing attributes.',
      'Inspect the captured request and Set-Cookie attributes for the affected host.', 'Use secure transport and appropriate Secure, HttpOnly and SameSite attributes.'],
  ],
  'Sensitive Data Exposed in Network Traffic': [
    ['Secret in URL or response', /^(TRAFFIC_SECRET_IN_URL|TRAFFIC_SECRET_IN_RESPONSE)/,
      'A secret may appear in a URL or response body.', 'URLs can enter logs and history; responses may expose data to an unintended client if access control is wrong.',
      'Confirm the value type and recipient using a benign account or redacted capture.', 'Move tokens out of URLs and return only the fields required by the client.'],
    ['WebSocket secret', /^TRAFFIC_WS_SECRET/,
      'A WebSocket URL or message may carry sensitive data.', 'The value may reach logs or unauthorised subscribers depending on server routing.',
      'Record the socket endpoint and the message recipient without disclosing the secret itself.', 'Authenticate with a short-lived ticket or message and authorise each recipient.'],
    ['Third-party destination', /^(TRAFFIC_AUTH_TO_THIRD_PARTY|TRAFFIC_USER_INPUT_TO_THIRD_PARTY)/,
      'Credentials or user input may be sent to a host outside the expected first-party set.', 'If the host is genuinely third party, it may receive data the user did not intend to share.',
      'Confirm host ownership, request purpose and whether the value can be removed or minimised.', 'Constrain authentication headers to the intended API and minimise third-party data.'],
  ],
  'Outdated Electron Runtime': [
    ['Unsupported release line', /^UNSUPPORTED_VERSION/,
      'The installed Electron major version may no longer receive support.', 'Future vulnerabilities may remain unpatched on that line.',
      'Confirm the packaged version and the current supported release lines.', 'Upgrade to a supported Electron major and test the app’s compatibility.'],
    ['Missing Electron or Chromium fixes', /^(AVAILABLE_SECURITY_FIXES|CHROMIUM_ADVISORIES)/,
      'The installed build may predate security fixes in Electron or its Chromium runtime.', 'Exploitability depends on the affected browser feature and whether the app exposes it.',
      'Compare the exact bundled versions and applicable advisories, including backports.', 'Upgrade to a release containing the relevant fixes and rescan the package.'],
  ],
  'Outdated Third-Party Components': [
    ['Published dependency advisory', /^DEPENDENCY_VULNERABILITIES/,
      'An installed package version matches one or more published advisories.', 'The impact depends on whether the vulnerable code path is present and reachable in this app.',
      'Match package and version to advisory conditions and the affected import or bundle.', 'Upgrade to the fixed version listed in the component spreadsheet.'],
    ['Unsupported library', /^END_OF_LIFE_LIBRARY/,
      'A library release line is no longer maintained.', 'The absence of future fixes increases exposure even where no current exploit is demonstrated.',
      'Confirm the shipped copy and its support status; check whether it is used at runtime.', 'Replace or upgrade the library to a maintained release.'],
  ],
  'Known Malicious Package': [
    ['Malicious version in inventory', /^MALICIOUS_DEPENDENCY/,
      'A specific installed package version is listed as malicious.', 'If installed or executed during the build, it could have accessed build credentials or modified artefacts.',
      'Confirm the exact version, source, installation time and any install scripts or build use.', 'Remove the version, rebuild from trusted dependencies and investigate the build environment.'],
    ['Exposure response', /^MALICIOUS_DEPENDENCY/,
      'The response scope may extend beyond the shipped application.', 'Secrets available on affected developer or CI machines may need rotation if the package executed there.',
      'Review package execution and access logs before deciding which credentials and artefacts were exposed.', 'Rotate potentially exposed credentials and verify release artefacts from a clean build.'],
  ],
};

/** Variations supported by the checks in this group, including multiple plausible outcomes of one check. */
export function matchingVariations(title, issues, normalise) {
  const entries = VARIATIONS[title] || [];
  const matched = entries.map(([label, pattern, description, implication, evidence, recommendation]) => ({
    label, description, implication, evidence, recommendation, issues: issues.filter(i => pattern.test(normalise(i.id))),
  })).filter(v => v.issues.length);
  // A newly added check or catch-all observation still receives a complete variation across every section.
  for (const issue of issues) if (!matched.some(v => v.issues.includes(issue))) matched.push({
    label: issue.id, description: issue.description || 'Additional observation.',
    implication: 'The impact depends on the affected operation and whether a lower-trust actor can reach it.',
    evidence: 'Inspect the recorded location and confirm the actual input source and behaviour.',
    recommendation: 'Address the recorded check according to its specific remediation guidance.', issues: [issue],
  });
  return matched;
}
