// How to fix each kind of finding, shown with the finding in every report (HTML, JSON, Word and the shareable report).
// Keyed like consequences.js: the check id without its _JS_CHECK / _HTML_CHECK / _JSON_CHECK / _GLOBAL_CHECK suffix.
// Each entry is [what to do, an example] and the example is optional. Inventory findings (route "info") have none:
// there is nothing to fix in them. Runtime and traffic findings that prove a static finding share its advice (ALIASES).
const REMEDIATION = {
  RUNTIME_CERTIFICATE_PROOF: ['Preserve certificate chain/hostname verification, remove bypass switches and fail closed in certificate verification callbacks.'],
  RUNTIME_FUSE_PROOF: ['Disable unnecessary RunAsNode and CLI inspector fuses at packaging time, then repeat the behavioral probe on the rebuilt executable.'],
  RUNTIME_IPC_PROOF: ['Review the tested handler’s sender allowlist and path policy; validate actual senderFrame origins and constrain reads to approved files.'],
  RUNTIME_SHELL_PROOF: ['Allow only the URL schemes and file paths required by the app before handing them to shell APIs.'],
  RUNTIME_UPDATE_PROOF: ['Use HTTPS for every feed hop and verify artifact hashes and publisher signatures in the actual updater.'],
  WINDOWS_INSTALL_PERMISSIONS: ['Review effective rights for the intended attacker account and restrict modification of executable, DLL and resource paths to the intended installation owner or administrators.'],
  WINDOWS_PROTOCOL_REGISTRATION: ['Quote the executable and URL placeholder, separate URL arguments from switches where supported, and validate all initial/second-instance arguments against an explicit protocol policy.'],
  DYNAMIC_MODULE: ['Keep renderer input out of require() and import() paths. Map an allowlisted identifier to a fixed module, and reject unknown identifiers before loading anything.'],
  AFFINITY: ['Remove the affinity option so each window gets its own renderer process (it was removed in Electron 14).'],
  ALLOWPOPUPS: ['Remove the allowpopups attribute from the <webview>, or handle new-window requests and deny what the app does not need.'],
  ANGULAR_BIND_HTML_UNSAFE: ['Bind text with interpolation ({{ value }}) or ng-bind. If HTML is required, sanitize it first (ngSanitize or DOMPurify) and bind the sanitized result.'],
  ANGULAR_RESOURCE_URL_LIST: ['Restrict $sceDelegateProvider.resourceUrlWhitelist to "self" and the exact HTTPS hosts templates come from; never use wildcards.'],
  ANGULAR_SCE_DISABLED: ['Remove $sceProvider.enabled(false) so Angular keeps escaping bound values.'],
  ANGULAR_TRUST_HTML: ['Do not call $sce.trustAsHtml or $compile on stored or user-supplied content. Sanitize with DOMPurify (or ngSanitize) and bind the sanitized text.'],
  AUXCLICK: ['Disable middle-click window opening.', 'webPreferences: { disableBlinkFeatures: \'Auxclick\' }'],
  AVAILABLE_SECURITY_FIXES: ['Upgrade Electron to the newest release of a supported major version, then re-run the scan.'],
  BLINK_FEATURES: ['Remove blinkFeatures / enableBlinkFeatures from webPreferences and the command line; keep only what is documented as safe.'],
  CERTIFICATE_ERROR_EVENT: ['Do not call callback(true) for the certificate-error event. Let the load fail, and pin the expected certificate if a private CA is used.',
    'app.on(\'certificate-error\', (event, wc, url, error, cert, callback) => { callback(false); });'],
  CERTIFICATE_PINNING: ['Pin the server\'s public-key hash in session.setCertificateVerifyProc and fail closed on a mismatch.',
    'session.defaultSession.setCertificateVerifyProc((req, cb) => cb(pins.has(spkiHash(req.certificate)) ? 0 : -2));'],
  CERTIFICATE_VERIFY_PROC: ['Do not return success (0) for every certificate in setCertificateVerifyProc; verify the chain, or fall back to Chromium\'s result (-3), and reject mismatches (-2).'],
  COMMAND_INJECTION: ['Never build a command line from input. Use execFile or spawn with an argument array and no shell, validate each argument against an allowlist, and prefer a library call to a command.',
    'execFile(\'converter\', [\'--input\', validatedPath]);   // not exec(`converter ${name}`)'],
  CONTEXT_BRIDGE_EXPOSURE: ['Expose one narrow function per action through contextBridge, validate its arguments in the main process, and never expose ipcRenderer, require or send/on wrappers that accept any channel name.',
    'contextBridge.exposeInMainWorld(\'api\', { openDocument: (id) => ipcRenderer.invoke(\'document:open\', String(id)) });'],
  CONTEXT_ISOLATION: ['Turn contextIsolation on (the default since Electron 12) and give the page only what it needs through contextBridge in the preload script.',
    'webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true, preload: path.join(__dirname, \'preload.js\') }'],
  CSP: ['Serve a Content-Security-Policy with every page, from a <meta> tag or the response headers, and start strict.',
    `session.defaultSession.webRequest.onHeadersReceived((d, cb) => cb({ responseHeaders: { ...d.responseHeaders, 'Content-Security-Policy': ["default-src 'self'; script-src 'self'; object-src 'none'; base-uri 'none'"] } }));`],
  CSP_DIRECTIVES: ['Remove \'unsafe-inline\', \'unsafe-eval\', wildcards and data: from script-src (and from default-src), use hashes or nonces for the scripts that remain, and add object-src \'none\' and base-uri \'none\'.'],
  CUSTOM_ARGUMENTS: ['Remove switches that weaken the browser (--no-sandbox, --disable-web-security, --ignore-certificate-errors, --remote-debugging-port, --disable-site-isolation-trials) from app.commandLine and the launcher.'],
  DANGEROUS_FUNCTIONS: ['Replace eval, new Function and setTimeout/setInterval with a string by real functions; parse data with JSON.parse; never run text that came from outside the app.'],
  DEPENDENCY_VULNERABILITIES: ['Update each listed package to a release that fixes its advisories (npm audit, npm update, or a targeted upgrade of the parent package), commit the lockfile, and re-run the scan. Where no fix exists, replace the package or reduce how it is used.'],
  DEVTOOLS: ['Disable DevTools in production builds.', 'webPreferences: { devTools: !app.isPackaged }'],
  DOCUMENT_PIPELINE: ['Treat documents as untrusted: validate type and size before opening, convert or preview them in a sandboxed process, and open them with the system viewer only after the user confirms.'],
  DOWNLOAD: ['Choose the save folder and a sanitized file name yourself (strip path separators), block executable types, and never open a downloaded file automatically.',
    'session.on(\'will-download\', (e, item) => item.setSavePath(path.join(downloads, path.basename(item.getFilename()))));'],
  END_OF_LIFE_LIBRARY: ['Upgrade the library to a supported version, or replace it; end-of-life releases no longer receive security fixes.'],
  EXPERIMENTAL_FEATURES: ['Remove experimentalFeatures (and experimental Chromium flags) from webPreferences.'],
  FILE_HANDLER: ['Treat the command line of a second instance, open-file and open-url events as untrusted input: parse strictly, allow only known schemes and folders, and never pass the value to a shell or to loadURL.'],
  FILE_PROTOCOL: ['Do not load remote or user-supplied content from file://. Serve local content through a custom scheme with protocol.handle and keep file:// privileges off (GrantFileProtocolExtraPrivileges fuse off).'],
  FUSES: ['Flip the insecure fuses at package time with @electron/fuses.',
    'flipFuses(exe, { version: FuseVersion.V1, [FuseV1Options.RunAsNode]: false, [FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false, [FuseV1Options.EnableNodeCliInspectArguments]: false, [FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true, [FuseV1Options.OnlyLoadAppFromAsar]: true, [FuseV1Options.EnableCookieEncryption]: true, [FuseV1Options.GrantFileProtocolExtraPrivileges]: false });'],
  HARDCODED_SECRET: ['Remove the secret from the package and rotate it now, because anyone with the app has it. Keep real secrets on a server; for keys that must ship, restrict them (by app, referrer or API) and give them the least scope.'],
  HTTP_RESOURCES: ['Load every script, style, frame and API over HTTPS (and WebSockets over wss://).'],
  HTTP_RESOURCES_WITH_NODE_INTEGRATION: ['Load only HTTPS content, and turn nodeIntegration off for any window that shows remote content.'],
  IFRAME_SANDBOX: ['Add a sandbox attribute to the iframe and never combine allow-scripts with allow-same-origin.', '<iframe sandbox="allow-forms" src="https://…"></iframe>'],
  INSECURE_CONTENT: ['Remove allowRunningInsecureContent and load everything over HTTPS.'],
  INSTALLER_FILE_HANDLER: ['Validate what the installer registers as a file or URL handler, and parse anything the app receives from it as untrusted input.'],
  IPC_FILE_ACCESS: ['Resolve the requested path against one base folder and reject anything that leaves it; never accept an absolute path or ../ from the renderer.',
    'const full = path.resolve(base, name); if (!full.startsWith(base + path.sep)) throw new Error(\'blocked\');'],
  AUTH_MODE_BYPASS: ['Apply the same authentication middleware in every build; give the desktop windows a per-session token instead of skipping the check.'],
  RUNTIME_LOCAL_SERVICE: ['Bind the local service to 127.0.0.1, allow cross-origin requests only from the application\'s own origins (never * or a reflected origin, and no chrome-extension:// wildcard), and require a per-session token.'],
  NODE_TLS_REJECT_UNAUTHORIZED_SCRIPT: ['Remove the launcher that sets NODE_TLS_REJECT_UNAUTHORIZED=0; to trust a private certificate authority, add it with NODE_EXTRA_CA_CERTS instead.'],
  CUSTOM_ARGUMENTS_SCRIPT: ['Remove the security-weakening switch from the shipped launcher script.'],
  IPC_RPC_PROCEDURE: ['Check the sender of every procedure call (the frame\'s URL against the app\'s own origin), validate inputs with the narrowest schema (paths kept inside an app folder, fixed proxy modes), and remove procedures the interface does not use.'],
  IPC_HANDLER: ['Validate the shape and type of every argument in the main process, give each channel one narrow job, keep shell, file and window access out of handlers that take page input, and never send credentials back to the page.'],
  IPC_SENDER_VALIDATION: ['Check who sent the message before acting on it: compare event.senderFrame.url\'s origin with your own, and ignore other frames.',
    'function validateSender(frame) { return new URL(frame.url).origin === \'app://main\'; }\nipcMain.handle(\'ch\', (e, ...args) => { if (!validateSender(e.senderFrame)) return; /* … */ });'],
  LIMIT_NAVIGATION: ['Block navigation away from your own pages and route external links through an allowlist.',
    'win.webContents.on(\'will-navigate\', (e, url) => { if (new URL(url).origin !== ownOrigin) e.preventDefault(); });'],
  NAVIGATE_ON_DRAG_DROP: ['Keep navigateOnDragDrop off (the default) so dropping a file or link does not navigate the window.'],
  NAVIGATION_REDIRECT: ['Also handle will-redirect (and did-start-navigation), not just will-navigate, so a server redirect cannot leave your allowlist.',
    'win.webContents.on(\'will-redirect\', (e, url) => { if (new URL(url).origin !== ownOrigin) e.preventDefault(); });'],
  NODE_INTEGRATION: ['Turn nodeIntegration off and move Node.js work into the main process behind narrow IPC handlers, with a preload script for the bridge.', 'webPreferences: { nodeIntegration: false, contextIsolation: true, sandbox: true }'],
  NODE_INTEGRATION_ATTACH_EVENT: ['In will-attach-webview, delete the preload and force nodeIntegration off, and validate params.src against an allowlist.',
    'contents.on(\'will-attach-webview\', (e, prefs, params) => { delete prefs.preload; prefs.nodeIntegration = false; if (!allowed(params.src)) e.preventDefault(); });'],
  NODE_TLS_REJECT_UNAUTHORIZED: ['Remove NODE_TLS_REJECT_UNAUTHORIZED=0 and fix the certificate problem itself (trust the right CA, use a valid certificate).'],
  OPEN_EXTERNAL: ['Parse the URL and open it only for allowed schemes and hosts; never pass raw page input to shell.openExternal.',
    'const u = new URL(url); if (u.protocol === \'https:\' && allowedHosts.has(u.hostname)) shell.openExternal(u.href);'],
  OPEN_PATH: ['Resolve the path against a base folder, reject anything outside it, block executable extensions, and prefer shell.showItemInFolder over opening the file. Check the result string, because openPath returns an error message instead of throwing.',
    'const full = path.resolve(base, name); if (!full.startsWith(base + path.sep) || /\\.(exe|bat|cmd|ps1|js|lnk|msi|scr)$/i.test(full)) return;'],
  PACKAGED_FUSES: ['Flip the insecure fuses at package time with @electron/fuses (see FUSES for the full list), then rebuild and re-scan the binary.',
    'flipFuses(exe, { version: FuseVersion.V1, [FuseV1Options.RunAsNode]: false, [FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false, [FuseV1Options.EnableNodeCliInspectArguments]: false, [FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true, [FuseV1Options.OnlyLoadAppFromAsar]: true, [FuseV1Options.EnableCookieEncryption]: true, [FuseV1Options.GrantFileProtocolExtraPrivileges]: false });'],
  PERMISSION_REQUEST_HANDLER: ['Set both permission handlers, allow only what the app needs and only for your own origin, and deny everything else.',
    'ses.setPermissionRequestHandler((wc, permission, cb, details) => cb(permission === \'notifications\' && new URL(details.requestingUrl).origin === ownOrigin));\nses.setPermissionCheckHandler((wc, permission, origin) => permission === \'notifications\' && origin === ownOrigin);'],
  PLAINTEXT_SECRETS: ['Do not store secrets in files, settings or the profile in plain text. Encrypt them with Electron\'s safeStorage (OS keychain backed), or keep them on the server and hold only a short-lived token.',
    'const blob = safeStorage.encryptString(token);   // store blob; decrypt with safeStorage.decryptString'],
  PLUGINS: ['Remove the plugins option; the browser plugin API is not needed by current apps.'],
  PROTOCOL_HANDLER: ['Treat deep-link URLs as untrusted: parse them, allow only known actions and hosts, and never pass them to loadURL, a shell or a file path unchecked.'],
  PROTOCOL_PRIVILEGES: ['Register custom schemes with the fewest privileges (avoid bypassCSP, and add secure/standard/supportFetchAPI only when needed) and serve only your own files from them.'],
  REMOTE_MODULE: ['Remove the remote module (it was removed from Electron 14) and replace each use with a narrow IPC handler.'],
  RICH_TEXT_EDITOR: ['Sanitize the editor\'s HTML on input and again on output (DOMPurify with a tight allowlist), and never render editor content in a window that has Node.js access.'],
  SANDBOX: ['Turn the renderer sandbox on (the default since Electron 20) and do not combine it with nodeIntegration.', 'webPreferences: { sandbox: true }'],
  SANITIZER_CONFIG: ['Tighten the sanitizer: remove the option that allows scripts, event handlers or unknown protocols, and use the library\'s default allowlist plus only the tags you need.'],
  SECUREKEYBOARDENTRY: ['On macOS, turn on secure keyboard entry while a password field is focused.', 'app.setSecureKeyboardEntryEnabled(true)'],
  SHOWITEMINFOLDER: ['Validate the path before revealing it (resolve it against a base folder and reject anything outside it).'],
  UNSUPPORTED_VERSION: ['Upgrade Electron to a currently supported major version; unsupported versions get no security fixes.'],
  UNTRUSTED_LOAD_URL: ['Load only fixed HTTPS URLs or an allowlist of them. Never pass IPC, deep-link or user input to loadURL.',
    'if (allowedUrls.has(url)) win.loadURL(url);'],
  UPDATE_SECURITY: ['Serve updates over HTTPS only and verify their signatures before installing (code signing with electron-updater, or Squirrel with signed releases); never accept an update from a plain-HTTP feed.'],
  UPDATE_SECURITY_PACKAGED: ['Use an HTTPS update feed and check the update\'s signature or publisher name before installing it.'],
  WEBGL: ['Turn WebGL off for windows that do not need it.', 'webPreferences: { webgl: false }'],
  WEBSQL: ['Turn WebSQL off (enableWebSQL: false, the default since Electron 13) and migrate to IndexedDB.'],
  WEBVIEW: ['Avoid <webview>. Use an iframe with sandbox, or a WebContentsView/BrowserView with contextIsolation and sandbox on. If it must stay, lock it down in will-attach-webview.'],
  WEBVIEW_TAG: ['Avoid <webview>; if it is required, remove nodeintegration, disablewebsecurity and allowpopups, set a partition, and validate src.'],
  WEB_SECURITY: ['Remove webSecurity: false; fix cross-origin needs with CORS headers or a request handler instead.'],
  WINDOW_OPEN_HANDLER: ['Deny new windows by default and open only allowed HTTPS URLs in the system browser.',
    'win.webContents.setWindowOpenHandler(({ url }) => { if (isAllowed(url)) shell.openExternal(url); return { action: \'deny\' }; });'],
  WINDOW_SESSION: ['Give windows that show different levels of trust separate sessions (webPreferences.partition) so cookies, storage and permission handlers are not shared.'],
  WORD_LAUNCH: ['Do not build a command line from a document name. Open documents with shell.openPath after validating the path, or start the program with execFile and an argument array.',
    'execFile(wordPath, [\'/r\', validatedPath]);   // not exec(`start winword "${name}"`)'],
  WRITE_SHORTCUT: ['Validate the shortcut\'s target and location (fixed folder, allowed target) before creating it.'],
  HTML_TEMPLATE: ['Escape every value for where it goes (element text: & < >; attribute values: also quotes), or build the document with DOM methods (textContent, setAttribute) instead of a string template.', 'const title = document.createElement(\'h1\');\ntitle.textContent = note.title;'],
  RENDERER_INPUT: ['Treat pasted, dropped and opened content as untrusted: sanitise HTML before inserting it and validate file names and types before using them.'],
  XSS_SINK: ['Write text with textContent or a framework binding instead of innerHTML, document.write or insertAdjacentHTML. Where HTML is required, sanitize it with DOMPurify first.',
    'el.textContent = value;   // or el.innerHTML = DOMPurify.sanitize(value)'],
  ASAR_INTEGRITY: ['Enable the EnableEmbeddedAsarIntegrityValidation and OnlyLoadAppFromAsar fuses and embed the asar integrity digest at package time, so a modified app.asar is refused.'],
  BINARY_HARDENING: ['Ship the official Electron binaries built with current mitigations, and build native modules with the platform hardening flags on (Windows: ASLR, DEP, Control Flow Guard; Linux: PIE, stack protector, RELRO, NX).'],
  CHROMIUM_ADVISORIES: ['Upgrade Electron to a release whose Chromium includes the fixes (newest release of a supported major version), and re-run the scan.'],
  CODE_SIGNING: ['Sign the executable and installer with a trusted certificate (Windows Authenticode, macOS Developer ID plus notarization) and timestamp the signature.'],
  COOKIE_FLAGS: ['Set Secure, HttpOnly and SameSite on session cookies, and turn on the EnableCookieEncryption fuse.'],
  ELECTRON_STORE_ENCRYPTION: ['The encryptionKey option only obfuscates the file (the key ships in the app). Store secrets with safeStorage instead and keep the config file free of them.'],
  MALICIOUS_DEPENDENCY: ['Remove the package, delete node_modules and the lockfile entry, reinstall from a trusted source, rotate every secret the machine or build could have exposed, and review how it got in.'],
  SECRET_FILE_WRITE: ['Do not write secrets to disk in plain text; use safeStorage, or the OS credential store, and delete any file that already holds one.'],
  SOURCE_MAP_SHIPPED: ['Exclude .map files from the package (and strip sourceMappingURL comments), or keep them on a private server for error reporting.'],
  DEVELOPMENT_CODE: ['Remove development-only code, flags and test hooks from production builds (build-time flags, not runtime checks).'],
  DEBUG_LOGGING: ['Do not log secrets, tokens or personal data; lower log levels in production and keep logs out of the console and the profile folder.'],
  STORAGE_CACHED_RESPONSES: ['Send Cache-Control: no-store on responses that hold sensitive data, and clear the cache on sign-out.'],
  STORAGE_COOKIE_AT_REST: ['Turn on the EnableCookieEncryption fuse, and keep long-lived credentials out of cookies (short lifetimes, server-side revocation).'],
  STORAGE_CREDENTIAL_AT_REST: ['Do not save the user\'s password. Store a revocable token with safeStorage (or the OS credential store) and clear it on sign-out.'],
  STORAGE_SECRET_AT_REST: ['Move the secret out of the profile folder: encrypt with safeStorage, or keep it on the server. Rotate any secret that was stored in plain text.'],
  TRAFFIC_AUTH_TO_THIRD_PARTY: ['Send the Authorization header only to your own API origin (check the request\'s host before adding it) and use scoped, short-lived tokens for third parties.'],
  TRAFFIC_BASIC_AUTH: ['Replace Basic authentication with token-based sign-in, and never send it over plain HTTP.'],
  TRAFFIC_CLEARTEXT_HTTP: ['Use HTTPS for all requests, and add HSTS on the server.'],
  TRAFFIC_IDOR_CANDIDATE: ['Check on the server that the signed-in user may access the object id in each request (ownership or role), rather than trusting the id.'],
  TRAFFIC_INSECURE_COOKIE: ['Set Secure, HttpOnly and SameSite on the cookie.'],
  TRAFFIC_REFLECTED_INPUT: ['Encode the value for the place it is written (HTML, attribute, JavaScript or URL), or reject it, before returning it in a response.'],
  TRAFFIC_SECRET_IN_RESPONSE: ['Do not return secrets, tokens or other users\' data in API responses; return only what the client needs.'],
  TRAFFIC_SECRET_IN_URL: ['Move tokens and keys from the URL into the Authorization header or the request body; URLs end up in logs, history and Referer headers.'],
  TRAFFIC_STATE_CHANGE_NO_AUTH: ['Require authentication and authorization for every state-changing request, and add anti-CSRF protection (tokens or SameSite cookies).'],
  TRAFFIC_USER_INPUT_TO_THIRD_PARTY: ['Stop sending user-entered data to analytics and other third parties, or strip and hash it first, and get consent where the law requires it.'],
  TRAFFIC_WS_CLEARTEXT: ['Use wss:// instead of ws://.'],
  TRAFFIC_WS_HTML_MESSAGE: ['Do not render WebSocket messages as HTML. Use textContent, or sanitize with DOMPurify.'],
  TRAFFIC_WS_SECRET_IN_MESSAGE: ['Do not broadcast secrets or other users\' data over the socket; authorize each message on the server.'],
  TRAFFIC_WS_SECRET_IN_URL: ['Move the token out of the WebSocket URL: authenticate with the first message or a short-lived ticket.'],
  RUNTIME_HTML_ENDPOINT: ['Sanitize or encode the markup on the server before storing or returning it, and make every client render it as text unless it has been sanitized.'],
  RUNTIME_PRELOAD_FOREIGN_ORIGIN: ['Attach preload scripts only to windows that show your own origin: block navigation to other sites in that window, and make the preload check the sender\'s origin before it answers.'],
};

// Runtime findings prove a static finding; the fix is the same.
const ALIASES = {
  RUNTIME_CSP: 'CSP', RUNTIME_CSP_VIOLATION: 'CSP', RUNTIME_CONTEXT_ISOLATION: 'CONTEXT_ISOLATION', RUNTIME_NODE_INTEGRATION: 'NODE_INTEGRATION',
  RUNTIME_SANDBOX: 'SANDBOX', RUNTIME_WEBVIEW: 'WEBVIEW', RUNTIME_WEB_SECURITY: 'WEB_SECURITY', RUNTIME_OPEN_EXTERNAL: 'OPEN_EXTERNAL',
  RUNTIME_MARKER_OPEN_EXTERNAL: 'OPEN_EXTERNAL', RUNTIME_OPEN_PATH: 'OPEN_PATH', RUNTIME_MARKER_OPEN_PATH: 'OPEN_PATH', RUNTIME_NAVIGATION: 'LIMIT_NAVIGATION',
  RUNTIME_MARKER_NAVIGATION: 'LIMIT_NAVIGATION', RUNTIME_REDIRECT: 'NAVIGATION_REDIRECT', RUNTIME_NEW_WINDOW: 'WINDOW_OPEN_HANDLER',
  RUNTIME_MARKER_NEW_WINDOW: 'WINDOW_OPEN_HANDLER', RUNTIME_PERMISSION: 'PERMISSION_REQUEST_HANDLER', RUNTIME_PERMISSION_CHECK: 'PERMISSION_REQUEST_HANDLER',
  RUNTIME_CERTIFICATE_ERROR: 'CERTIFICATE_ERROR_EVENT', RUNTIME_INSECURE_LOAD: 'INSECURE_CONTENT', RUNTIME_DOM_INJECTION: 'XSS_SINK', RUNTIME_IFRAME: 'IFRAME_SANDBOX', RUNTIME_MARKER_SINK: 'XSS_SINK', RUNTIME_MARKER_MODULE: 'DYNAMIC_MODULE',
  RUNTIME_MARKER: 'XSS_SINK', RUNTIME_MARKER_COMMAND: 'COMMAND_INJECTION', RUNTIME_MARKER_IPC: 'IPC_SENDER_VALIDATION', RUNTIME_WINDOW_SESSION: 'WINDOW_SESSION',
  RUNTIME_SECRET_IN_CONSOLE: 'DEBUG_LOGGING',
};

const baseId = (id) => String(id || '').replace(/_(JS|HTML|JSON|GLOBAL)_CHECK$/, '').replace(/_LOCK_CHECK$/, '');

/** { fix, example } for a finding's check id, or undefined when there is nothing to fix (inventories, coverage notes). */
export function remediationOf(id) {
  const base = baseId(id);
  const entry = REMEDIATION[id] || REMEDIATION[base] || REMEDIATION[ALIASES[id]] || REMEDIATION[ALIASES[base]];
  if (entry) return { fix: entry[0], example: entry[1] };
  if (/_(REMOVAL|DEPRECATION|DEFAULT_CHANGE)$/.test(String(id))) return { fix: 'Follow the migration note in the linked Electron breaking-changes entry before upgrading.' };
  return undefined;
}

/** The check ids that have their own advice (for the test that keeps this in step with consequences.js). */
export const REMEDIATION_IDS = [...Object.keys(REMEDIATION), ...Object.keys(ALIASES)];
